In [4]:
import numpy as np

# slice and broadcast

my_arr = np.random.randint(0, 10, 10)

#broadcasts 0 - 4 index to 100
my_arr[0:5] = 100
my_arr

array([100, 100, 100, 100, 100,   4,   4,   1,   9,   3], dtype=int32)

In [6]:
temp_arr = my_arr
temp_arr[:] = 99 #this will also change the original my_arr
my_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99], dtype=int32)

In [8]:
#to avoid changing use copy()
copy_arr = my_arr.copy()
copy_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99], dtype=int32)

In [12]:
copy_arr[:] = 50 #wont change original my_arr
copy_arr

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50], dtype=int32)

In [13]:
my_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99], dtype=int32)

In [16]:
#slicing in matrix
matrix = np.array([[5,10,5], [15, 5, 10], [10,10,5]])
matrix

array([[ 5, 10,  5],
       [15,  5, 10],
       [10, 10,  5]])

In [17]:
matrix[1:]

array([[15,  5, 10],
       [10, 10,  5]])

In [18]:
matrix[1:, 1:]

array([[ 5, 10],
       [10,  5]])

In [19]:
matrix[1:, :2]

array([[15,  5],
       [10, 10]])

In [20]:
#conditional selecting of array elems
arr = np.arange(1, 11)

bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [23]:
#simpler expression
arr[arr > 5]

array([ 6,  7,  8,  9, 10])