In [3]:
my_arr = [1,2,3]

#cast as numpy arr

import numpy as np

arr = np.array(my_arr)
arr

array([1, 2, 3])

In [5]:
#matrices
my_mat = [[1,2,3],[4,5,6], [7,8,9]]
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#arrange
nums1 = np.arange(0, 10)
nums1

nums2 = np.arange(1, 20, 2)
nums2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
zeros = np.zeros(10)
zeros

matrixOnes = np.ones((2,3))
matrixOnes

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#evenly spaced points between two numbers
# 10 evenly spaced points between 1 and 8:
np.linspace(0, 8, 10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [22]:
#identity matrix'
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
#random number arrays

#1. 5 random numbers between 0-1
np.random.rand(5)

#2. Matrix 5x5 of numbers between 0-1
np.random.rand(5,5)

#3. random number from normal distribution centered at 0
np.random.randn(4)

#4. random integers from a given low, high, length
np.random.randint(0, 100,10)

array([63,  5,  9, 54, 62,  9, 45, 73, 90, 30], dtype=int32)

In [47]:
#methods

#1. reshape() an array into a matrix of equivalent size
my_arr = np.arange(25)
my_arr.reshape(5,5)

#2. max, min
randomInt = np.random.randint(1, 100, 10)
print(randomInt.max())
print(randomInt.min())


randomInt.argmax
randomInt.argmin


70
11


<function ndarray.argmin>

98
10
